// Simple fallback data that will always work
export const simpleDevelopers = [
  {
    _id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    bio: 'Full-stack developer with 5 years of experience in React and Node.js',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    skills: ['React', 'TypeScript', 'Node.js', 'MongoDB'],
    experience: 'senior',
    github: 'https://github.com/johndoe',
    linkedin: 'https://linkedin.com/in/johndoe',
    portfolio: 'https://johndoe.dev',
    isActive: true
  },
  {
    _id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    bio: 'UI/UX designer turned frontend developer, passionate about creating beautiful user experiences',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400',
    skills: ['React', 'CSS', 'Figma', 'TypeScript'],
    experience: 'intermediate',
    github: 'https://github.com/janesmith',
    linkedin: 'https://linkedin.com/in/janesmith',
    portfolio: 'https://janesmith.dev',
    isActive: true
  },
  {
    _id: '3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    bio: 'Backend developer specializing in scalable systems and cloud architecture',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    skills: ['Python', 'AWS', 'Docker', 'PostgreSQL'],
    experience: 'senior',
    github: 'https://github.com/mikejohnson',
    linkedin: 'https://linkedin.com/in/mikejohnson',
    portfolio: 'https://mikejohnson.dev',
    isActive: true
  }
];

export const simpleProjects = [
  {
    _id: '1',
    title: 'E-Commerce Platform',
    shortDescription: 'Modern e-commerce platform with React and Node.js',
    description: 'Full-featured e-commerce platform with payment integration',
    category: 'web',
    price: 49,
    techStack: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    features: ['Payment Integration', 'Admin Dashboard', 'Responsive Design'],
    images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/ecommerce',
    difficulty: 'intermediate',
    isFree: false,
    isPublished: true,
    downloads: 1250,
    purchases: 89,
    rating: 4.5,
    tags: ['ecommerce', 'react', 'nodejs'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15'
  },
  {
    _id: '2',
    title: 'Task Management App',
    shortDescription: 'Collaborative task management with real-time updates',
    description: 'Real-time task management application with team collaboration',
    category: 'web',
    price: 0,
    techStack: ['React', 'Firebase', 'Tailwind CSS'],
    features: ['Real-time Updates', 'Team Collaboration', 'Drag & Drop'],
    images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/tasks',
    difficulty: 'beginner',
    isFree: true,
    isPublished: true,
    downloads: 2100,
    purchases: 156,
    rating: 4.8,
    tags: ['tasks', 'collaboration', 'firebase'],
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10'
  },
  {
    _id: '3',
    title: 'Weather Dashboard',
    shortDescription: 'Beautiful weather dashboard with forecasts',
    description: 'Interactive weather dashboard with detailed forecasts',
    category: 'web',
    price: 0,
    techStack: ['Vue.js', 'Chart.js', 'OpenWeather API'],
    features: ['Weather Forecasts', 'Interactive Charts', 'Location Search'],
    images: ['https://images.unsplash.com/photo-1592210454359-1d8b3b9c8db3?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/weather',
    difficulty: 'beginner',
    isFree: true,
    isPublished: true,
    downloads: 1800,
    purchases: 98,
    rating: 4.6,
    tags: ['weather', 'dashboard', 'charts'],
    createdAt: '2024-01-08',
    updatedAt: '2024-01-08'
  },
  {
    _id: '4',
    title: 'Social Media Analytics',
    shortDescription: 'Analytics dashboard for social media metrics',
    description: 'Comprehensive analytics for social media performance',
    category: 'web',
    price: 79,
    techStack: ['React', 'D3.js', 'Node.js', 'PostgreSQL'],
    features: ['Data Visualization', 'Export Reports', 'Real-time Data'],
    images: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/analytics',
    difficulty: 'advanced',
    isFree: false,
    isPublished: true,
    downloads: 950,
    purchases: 67,
    rating: 4.7,
    tags: ['analytics', 'social-media', 'charts'],
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20'
  },
  {
    _id: '5',
    title: 'Chat Application',
    shortDescription: 'Real-time chat with video calling',
    description: 'Feature-rich chat application with video capabilities',
    category: 'web',
    price: 0,
    techStack: ['React', 'WebRTC', 'Socket.io', 'Express'],
    features: ['Video Calling', 'File Sharing', 'End-to-end Encryption'],
    images: ['https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/chat',
    difficulty: 'intermediate',
    isFree: true,
    isPublished: true,
    downloads: 3200,
    purchases: 234,
    rating: 4.9,
    tags: ['chat', 'video', 'real-time'],
    createdAt: '2024-01-05',
    updatedAt: '2024-01-05'
  },
  {
    _id: '6',
    title: 'Portfolio Template',
    shortDescription: 'Modern portfolio template for developers',
    description: 'Responsive portfolio template with animations',
    category: 'web',
    price: 0,
    techStack: ['React', 'Framer Motion', 'Tailwind CSS'],
    features: ['Smooth Animations', 'Project Showcase', 'Contact Form'],
    images: ['https://images.unsplash.com/photo-1547651321-19e4cd64ed05?w=400'],
    demoLink: 'https://demo.example.com',
    githubLink: 'https://github.com/example/portfolio',
    difficulty: 'beginner',
    isFree: true,
    isPublished: true,
    downloads: 4500,
    purchases: 312,
    rating: 4.4,
    tags: ['portfolio', 'template', 'animations'],
    createdAt: '2024-01-12',
    updatedAt: '2024-01-12'
  }
];
