-- Add More Projects (8-9 total projects)
-- Run this in Supabase SQL Editor

INSERT INTO projects (
  title,
  description,
  short_description,
  price,
  category,
  tech_stack,
  features,
  images,
  demo_link,
  github_link,
  difficulty,
  is_free,
  is_published,
  downloads,
  purchases,
  rating,
  tags,
  added_by
) VALUES
(
  'Blog Platform',
  'A modern blogging platform with markdown support, user authentication, and comment system. Features include draft posts, scheduled publishing, and analytics dashboard.',
  'Modern blog platform with markdown and analytics',
  39.99,
  'web',
  ARRAY['React', 'Node.js', 'MongoDB', 'Markdown', 'Tailwind CSS'],
  ARRAY['Markdown Editor', 'User Authentication', 'Comment System', 'Draft Posts', 'Analytics Dashboard'],
  ARRAY['https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=400&fit=crop'],
  'https://blog-demo.blitzs.dev',
  'https://github.com/blitzs/blog-platform',
  'beginner',
  false,
  true,
  89,
  56,
  4.3,
  ARRAY['blog', 'cms', 'markdown', 'react'],
  (SELECT id FROM profiles WHERE email = 'sarah@blitzs.dev' LIMIT 1)
),
(
  'Recipe Finder',
  'A recipe discovery app with search, filters, and meal planning. Includes ingredient substitution suggestions and nutritional information.',
  'Recipe discovery app with meal planning features',
  19.99,
  'web',
  ARRAY['React', 'TypeScript', 'Edamam API', 'Tailwind CSS'],
  ARRAY['Recipe Search', 'Meal Planning', 'Nutritional Info', 'Ingredient Substitution', 'Favorites'],
  ARRAY['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=400&fit=crop'],
  'https://recipe-demo.blitzs.dev',
  'https://github.com/blitzs/recipe-finder',
  'beginner',
  false,
  true,
  156,
  98,
  4.6,
  ARRAY['recipe', 'food', 'api', 'planning'],
  (SELECT id FROM profiles WHERE email = 'mike@blitzs.dev' LIMIT 1)
),
(
  'Fitness Tracker',
  'A comprehensive fitness tracking app with workout plans, progress tracking, and social features. Includes exercise library and nutrition tracking.',
  'Fitness tracking app with workout plans and social features',
  59.99,
  'mobile',
  ARRAY['React Native', 'Firebase', 'Redux', 'Chart.js'],
  ARRAY['Workout Plans', 'Progress Tracking', 'Social Features', 'Exercise Library', 'Nutrition Tracking'],
  ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=400&fit=crop'],
  'https://fitness-demo.blitzs.dev',
  'https://github.com/blitzs/fitness-tracker',
  'intermediate',
  false,
  true,
  234,
  145,
  4.7,
  ARRAY['fitness', 'health', 'mobile', 'tracking'],
  (SELECT id FROM profiles WHERE email = 'david@blitzs.dev' LIMIT 1)
),
(
  'Chat Application',
  'Real-time chat application with rooms, private messaging, and file sharing. Features include online status, typing indicators, and message history.',
  'Real-time chat app with rooms and file sharing',
  44.99,
  'web',
  ARRAY['React', 'Node.js', 'Socket.io', 'MongoDB', 'WebRTC'],
  ARRAY['Real-time Chat', 'Private Messaging', 'File Sharing', 'Online Status', 'Message History'],
  ARRAY['https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=400&fit=crop'],
  'https://chat-demo.blitzs.dev',
  'https://github.com/blitzs/chat-application',
  'intermediate',
  false,
  true,
  312,
  189,
  4.5,
  ARRAY['chat', 'messaging', 'realtime', 'websockets'],
  (SELECT id FROM profiles WHERE email = 'emily@blitzs.dev' LIMIT 1)
),
(
  'Portfolio Template',
  'A beautiful portfolio template for developers and designers. Includes project showcase, blog, contact form, and dark mode support.',
  'Professional portfolio template with blog and dark mode',
  29.99,
  'web',
  ARRAY['React', 'Next.js', 'Tailwind CSS', 'Framer Motion'],
  ARRAY['Project Showcase', 'Blog Integration', 'Contact Form', 'Dark Mode', 'Responsive Design'],
  ARRAY['https://images.unsplash.com/photo-1460995809289-5d5a576a95b?w=800&h=400&fit=crop'],
  'https://portfolio-demo.blitzs.dev',
  'https://github.com/blitzs/portfolio-template',
  'beginner',
  false,
  true,
  445,
  267,
  4.8,
  ARRAY['portfolio', 'template', 'developer', 'design'],
  (SELECT id FROM profiles WHERE email = 'sarah@blitzs.dev' LIMIT 1)
);

-- Verify all projects
SELECT COUNT(*) as total_projects FROM projects WHERE is_published = true;
